### ISSUE TITLE
Add syntax coloring customization

### ISSUE THREAD

**Issue by vladchuk** [dart4e/dart4e#28]
Please add custom syntax coloring for Dart. The default might look fine in dark themes but it is pretty dismal in light ones.

**Comment by sebthom** [comment]
This is out of scope of this plugin as syntax coloring is done by [Eclipse TM4E](https://github.com/eclipse/tm4e/). To change colors you can/need to create a custom theme, e.g. https://github.com/eclipse/tm4e/tree/main/org.eclipse.tm4e.ui/themes

**Comment by vladchuk** [comment]
OK, I tried changing the color of class names in my custom theme but that has no effect, the color stays some nasty light green, impossible to see in the light theme.  

Specifically, I change the following without any luck. Could this be Dart specific?

`.entity.name.class { color: rgba(38, 139, 210, 1); }
.entity.name.type.class { color: rgba(38, 139, 210, 1); }
.entity.name.function { color: rgba(38, 139, 210, 1); }`

Are these the right rules to tweak or is there something else? Please let me know if I should be asking elsewhere.

**Comment by sebthom** [comment]
Please attach a screenshot of the editor showing the color you dislike.

**Comment by vladchuk** [comment]
![dart4e_colors](https://github.com/dart4e/dart4e/assets/4605991/5cad2007-ea9c-4a69-bc27-df5d1d2c73e1)

It's not so much that I dislike it as the fact that I can't change it, as described in my previous post.

I actually noticed that my custom style is in effect for about 5 seconds when the editor is first opened, then it reverts back to the colors in the screenshot. To be more precise, only the first editor keeps the custom color for that long, all subsequent ones revert to the default almost immediately. I hope this helps to troubleshoot.
