### ISSUE TITLE
Failed to update 'Dart Dependencies' list. Cannot create linked resource. 

### ISSUE THREAD

**Issue by cganoe** [dart4e/dart4e#51]
I keep seeing this error related to updating Dart Dependencies for whatever project I'm working on. I am guessing maybe it is a permissions related error on Mac OS, but that is just a guess.

If I manually create the folder it is complaining about, that error will go away, but it usually leads to more errors for other packages due to other missing dependencies. Also, nothing seems to get cached in the folders I manually create, so I'm not sure what the issue really is.

I erased my username in the screenshot, so the path in the message is /Users/[username]/.pub-cache/hosted/pub.dev etc.
![Screenshot 2024-07-29 at 9 48 10 AM](https://github.com/user-attachments/assets/61554ac2-56d8-4416-a149-3c0fdada0125)

**Comment by sebthom** [comment]
I am not a Mac user and don't have this issue. It looks like the dart dependencies are downloaded to a different/unexpected location and that's why they cannot be linked into the project explorer. When you run dart pub get, can you check where the dependencies are stored on your file system?

**Comment by cganoe** [comment]
It looks like the dependencies are being downloaded to the .pub-cache/hosted/pub.dev folder of the root of my Flutter SDK installation (which is not my home directory). 

When I look at my Eclipse project under Dart Dependencies, the list of dependencies is the same as what is in the .pub-cache/hosted/pub.dev folder of my Flutter SDK installation. The folders I created manually off my home directory
in /Users/[username]/.pub-cache/hosted/pub.dev/flutter_markdown-0.7.3 and /Users/[username]/.pub-cache/hosted/pub.dev/markdown-0.2.2 are showing up as empty in my Eclipse project explorer under Dart Dependencies. 

![Screenshot 2024-07-29 at 2 03 14 PM](https://github.com/user-attachments/assets/6c08c385-23d7-4b5b-a36d-571cb7f1423b)

**Comment by sebthom** [comment]
As a workaround you can set the `PUB_CACHE` environment variable either to
- `<flutter_sdk>/.pub-cache` which then be used by Dart4E, or
- `/Users/[username]/.pub-cache` which will then be used by Dart, Flutter and Dart4E.

**Comment by sebthom** [comment]
Based on the docs at https://dart.dev/tools/pub/environment-variables the default should be /Users/[username]/.pub-cache
I don't know why in your case the dependencies are downloaded into the Flutter SDK

**Comment by sebthom** [comment]
So the way how Flutter handles dependency downloads seems to be messy and does not follow the behaviour of Dart SDK (at least on Mac), there are several tickets
- https://github.com/flutter/flutter/issues/105697
- https://github.com/flutter/flutter/issues/53833
- https://github.com/flutter/flutter/issues/105257

So it looks like on Mac (but not on Windows) Flutter stores dependencies in the Flutter SDK installation folder.

I am going to "fix" that in dart4e by hardcoding the path to `<flutter_sdk>/.pub-cache` only on MacOS but I would recommend you to set the PUB_CACHE variable and point it to `$HOME/.pub-cache` so the cache is re-used across dart/flutter installations.

**Comment by sebthom** [comment]
Can you please give the latest snapshot build a try https://github.com/dart4e/dart4e/releases/download/preview/org.dart4e.plugin.updatesite.zip

**Comment by cganoe** [comment]
Sorry for the slow followup. I did try your snapshot out, and it seems to resolve the issue I was having. I was also having an issue where code completion wasn't working, and that seems to be resolved with your fix as well. 

There is not a good way to set an environment variable inside Eclipse on Mac OS. I will read through the links you provided and see if there is a good way to get everything looking at the same cache ($HOME/.pub-cache or elsewhere).
